services:
  - type: web
    name: capital-hospital-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_URI
        sync: false
      - key: DB_NAME
        value: capital_hospital
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_ORIGINS
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
